@baseUrl=http://localhost:3000

### Read one user
GET {{ baseUrl }}/

### Login
POST {{baseUrl}}/api/login
Content-Type: application/json

{
    "login": "admin",
    "password": "admin"
}

### Read one user
GET {{ baseUrl }}/dashboard
