@baseUrl=http://localhost:3000
@admin_token={{ admin.response.body.token }}

### Get /
GET {{ baseUrl }}/

### Login
# @name admin
POST {{baseUrl}}/api/login
Content-Type: application/json

{
    "login": "admin",
    "password": "admin"
}

### GET /dashboard
GET {{ baseUrl }}/dashboard
Authorization: {{admin_token}}
